#GunAura Both Config
#This module need both install this mod.
#The ammo free module of the GunAura module,the gun's the counts of ammo will at least 1 when this module enabled.
#无限火力
ammoFree = true
#This module need both install this mod.
#The no cool down module of the GunAura module,the gun's fire cool download will be to 0 when this module enabled.
#无攻击冷却
noCooldown = true

