#GunAura Client Config
#The range of the GunAura module,when the GunAura module enabled,it will get the nearest entity to attack in this range.
#范围
#Range: 0 ~ 1000
range = 1000
#The enable of the GunAura module.
enabled = true
#The forced auto module of the GunAura module,the gun's fire mode will forced to the auto mode when this module enabled.
#强制自动模式(无论枪械类型,即使是RPG也可以)
autoMode = true

